### PR TITLE
fix docker cluster issue with mesos 1.0.0

### LINKED ISSUE #84: docker cluster is broken due to new mesos release 1.0
There will be a fix PR soon. WIP. (https://ci.typesafe.com/job/mit-docker-test-ref/231/)

### PR DESCRIPTION
**Pull request by skonto**
-  fixes #84 
 - updates docker image to use xenial ubuntu repo

### CODE REVIEW

**Comment by skonto** [comment]
@deanwampler pls review.

File: mesos-docker/build/images/mesos/Dockerfile [hunk 1]
```diff
@@ -44,10 +44,10 @@ RUN apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
...
     echo $CODENAME && \
     echo $DISTRO && \
-    echo "deb http://repos.mesosphere.io/${DISTRO} trusty main" | tee /etc/apt/sources.list.d/mesosphere.list && \
+    echo "deb http://repos.mesosphere.io/${DISTRO} $CODENAME main" | tee /etc/apt/sources.list.d/mesosphere.list && \
     apt-get -y update && \
     VERSION=$(apt-cache madison mesos | head -1 | awk '{ print $3 }')  && \
-    MARATHON_VERSION=$(apt-cache madison marathon | head -1 | awk '{ print $3 }') && \
     apt-get -y install mesos=$VERSION && \
-    apt-get -y install marathon=$MARATHON_VERSION && \
+    curl -O http://downloads.mesosphere.com/marathon/v1.1.1/marathon-1.1.1.tgz && \
```
Comment (deanwampler) [inline mesos-docker/build/images/mesos/Dockerfile]: How about keeping the MARATHON_VERSION variable, but hard coding it to 1.1.1 for now?

File: mesos-docker/run/run.sh [hunk 2]
```diff
@@ -354,7 +355,7 @@ function start_slaves {
 
   for i in `seq 1 $NUMBER_OF_SLAVES`;
   do
-    start_slave_command="nohup /usr/local/bin/wrapdocker ; /usr/sbin/mesos-slave --master=$master --ip=$dip $(quote_if_non_empty $MESOS_SLAVE_CONFIG)"
+    start_slave_command="nohup /usr/local/bin/wrapdocker; /usr/sbin/mesos-slave --master=$master --work_dir=/tmp --ip=$dip $(quote_if_non_empty $MESOS_SLAVE_CONFIG)"
```
Comment (deanwampler) [inline mesos-docker/run/run.sh]: Does Mesos 1.0 still call the program `mesos-slave` or have they moved to the more neutral term, `mesos-agent` (or whatever)?

File: mesos-docker/build/images/mesos/Dockerfile (hunk 1 above)
Comment (skonto) [inline mesos-docker/build/images/mesos/Dockerfile]: good point I will fix it.

File: mesos-docker/run/run.sh (hunk 2 above)
Comment (skonto) [inline mesos-docker/run/run.sh]: Yes they do, but also kept those binaries. This code part is old not related to this pr. Maybe it would be good to update it in a new pr.

**Comment by deanwampler** [comment]
Thanks. Sounds good.

**Comment by skonto** [comment]
ready!

**Comment by deanwampler** [comment]
Looks great. Thanks.
